-- ============================================================================
-- KinetoFun — Re-seed 6 missing games
-- Run in the Supabase Dashboard → SQL Editor.
-- Safe to re-run (upsert on id).
-- ============================================================================

insert into public.games (
  id,
  title,
  tagline,
  description,
  short_description,
  category,
  category_id,
  players,
  min_players,
  max_players,
  cover,
  accent,
  rating,
  release_year,
  duration_minutes,
  difficulty,
  age_group,
  status,
  featured
)
values
  (
    'gesture-chef',
    'Gesture Chef',
    'Cook up a storm using nothing but your hands!',
    'Gesture Chef puts you in control of a virtual kitchen using hand gestures. Wave to chop, swipe to stir, and raise your hand to flip — follow on-screen recipes, manage timers, and plate every dish before the clock runs out. All controls are fully gesture-based; no mouse or keyboard required. Progress through increasingly complex recipes and earn chef stars for speed and precision.',
    'Cook virtual dishes with hand gestures — chop, stir, and plate your way to culinary stardom.',
    'Action',
    (select id from public.categories where slug = 'action' limit 1),
    'single',
    1,
    1,
    'from-orange-400 via-yellow-500 to-red-400',
    '#f97316',
    4.3,
    2026,
    10,
    'easy',
    '5+',
    'published',
    false
  ),
  (
    'dance-freeze',
    'Dance Freeze',
    'Dance when the music plays — freeze the instant it stops!',
    'Dance Freeze is a high-energy gesture party game. Dance freely while the beat plays, then hold perfectly still the moment the music cuts. The camera tracks your movement in real time — any detectable motion while frozen means you are out! Survive multiple elimination rounds, strike the silliest frozen poses, and outlast your personal best. Perfect for a quick energy burst or a classroom warm-up.',
    'Groove to the music and snap into a statue on cue — any movement when frozen knocks you out!',
    'Party',
    (select id from public.categories where slug = 'party' limit 1),
    'single',
    1,
    1,
    'from-pink-500 via-fuchsia-500 to-purple-600',
    '#ec4899',
    4.4,
    2026,
    8,
    'easy',
    '5+',
    'published',
    false
  ),
  (
    'funny-face-contest',
    'Funny Face Contest',
    'Pull the most ridiculous face you can — the AI will judge!',
    'Funny Face Contest uses MediaPipe face and hand tracking to score your silliest expressions in real time. On-screen prompts ask you to raise your eyebrows, stick out your tongue, puff your cheeks, or wink — the more exaggerated, the higher your score. Collect points across timed rounds, unlock wilder challenges, and compete for the ultimate Silly Face crown. Guaranteed to produce genuine laughter.',
    'Strike outrageous expressions on command and let the gesture AI score your silliness.',
    'Party',
    (select id from public.categories where slug = 'party' limit 1),
    'single',
    1,
    1,
    'from-yellow-400 via-orange-400 to-pink-500',
    '#fbbf24',
    4.2,
    2026,
    7,
    'easy',
    '4+',
    'published',
    false
  ),
  (
    'gesture-ludo-king',
    'Gesture Ludo King',
    'The classic board game — played entirely with hand gestures.',
    'Gesture Ludo King brings the beloved Ludo board game to life with full gesture controls. Wave your open hand to roll the dice, point to select a token, and swipe in the direction of travel to move it. Play against up to three AI opponents across beginner, medium, and expert difficulty levels. Classic Ludo rules apply — race your four tokens from start to home while sending rival tokens back to base. No touching required; pure gesture-based strategy fun.',
    'Play Ludo with hand gestures — wave to roll dice, point and swipe to move your tokens.',
    'Puzzle',
    (select id from public.categories where slug = 'puzzle' limit 1),
    'single',
    1,
    1,
    'from-blue-600 via-indigo-600 to-violet-700',
    '#6366f1',
    4.3,
    2026,
    20,
    'medium',
    '6+',
    'published',
    false
  ),
  (
    'magic-cleaning',
    'Magic Cleaning',
    'Sweep, scrub, and sparkle — all with a wave of your hand!',
    'Magic Cleaning is a satisfying gesture-based tidying game. Use sweeping arm motions to brush away dust, scrubbing gestures to polish stains, and pinching moves to pick up clutter and drop it in the right bins. Each level presents a messier room than the last, and a countdown timer keeps the pressure on. Earn a perfect clean rating by removing every speck before time runs out — then watch the room sparkle back to life.',
    'Sweep and scrub messy rooms back to perfection using magical hand gesture cleaning powers.',
    'Action',
    (select id from public.categories where slug = 'action' limit 1),
    'single',
    1,
    1,
    'from-cyan-400 via-teal-500 to-emerald-600',
    '#14b8a6',
    4.1,
    2026,
    8,
    'easy',
    '4+',
    'published',
    false
  ),
  (
    'rock-paper-scissors',
    'Rock Paper Scissors',
    'The classic hand game — now played with real hand gestures detected live.',
    'Rock Paper Scissors uses MediaPipe hand tracking to read your actual hand shape in real time. Make a tight fist for Rock, flatten your hand for Paper, or extend two fingers for Scissors — the camera sees your gesture instantly. Go head-to-head against a reactive AI opponent across best-of-5, best-of-7, or best-of-9 rounds. The AI ramps up its reaction speed as your win streak grows. No buttons, no delays — just raw hand-vs-AI gesture action.',
    'Throw a real fist, flat hand, or scissors and let the gesture AI determine who wins.',
    'Arcade',
    (select id from public.categories where slug = 'arcade' limit 1),
    'single',
    1,
    1,
    'from-slate-500 via-gray-600 to-zinc-700',
    '#64748b',
    4.5,
    2026,
    5,
    'easy',
    '5+',
    'published',
    false
  )
on conflict (id) do update set
  title             = excluded.title,
  tagline           = excluded.tagline,
  description       = excluded.description,
  short_description = excluded.short_description,
  category          = excluded.category,
  category_id       = excluded.category_id,
  players           = excluded.players,
  min_players       = excluded.min_players,
  max_players       = excluded.max_players,
  cover             = excluded.cover,
  accent            = excluded.accent,
  rating            = excluded.rating,
  release_year      = excluded.release_year,
  duration_minutes  = excluded.duration_minutes,
  difficulty        = excluded.difficulty,
  age_group         = excluded.age_group,
  status            = excluded.status,
  featured          = excluded.featured,
  updated_at        = now();
