-- ============================================================================
-- KinetoFun — Word Search: Hidden Words seed
-- Run in the Supabase Dashboard → SQL Editor.
-- Safe to re-run (upsert on id).
--
-- Scores wiring: `public.scores` already has a generic `game_id text
-- references public.games (id)` foreign key (see supabase/schema.sql). Once
-- this game is inserted below, POST /api/scores { gameId:
-- 'word-search-hidden-words', score } (called automatically by GameIframe ->
-- GAME_COMPLETE, wired in games/word-search-hidden-words/src/App.tsx via
-- window.parent.postMessage) will insert a row into public.scores with no
-- further setup.
-- ============================================================================

insert into public.games (
  id,
  title,
  tagline,
  description,
  short_description,
  category,
  category_id,
  players,
  min_players,
  max_players,
  cover,
  accent,
  rating,
  release_year,
  duration_minutes,
  difficulty,
  age_group,
  status,
  featured
)
values (
  'word-search-hidden-words',
  'Word Search: Hidden Words',
  'Hover, trace, and confirm with an open palm to hunt down every hidden word — no mouse, no clicks.',
  'Word Search: Hidden Words is a gesture-only word-search puzzle built from the ground up around '
  'webcam hand tracking, not adapted from touch or mouse controls. A strict selection state machine '
  '(IDLE -> HOVERED -> START_SELECTED -> TRACING -> CONFIRMING -> VALIDATED_SUCCESS/FAIL) governs every '
  'selection: hovering a fingertip over a letter for 400-600ms starts a trace, moving across the grid '
  'extends the path and locks its direction after the second letter, and an open-palm gesture (or '
  'lifting the hand off the grid for one second) confirms the word. A closed fist cancels the current '
  'trace. Words hide horizontally, vertically, and diagonally, forwards or backwards, across three '
  'difficulty tiers (Easy 8x8 straight-only, Medium 10x10 with diagonals and reversed words, Hard 12x12 '
  'with dense overlaps) generated by a deterministic word-placement engine. Four modes: Classic (find '
  'everything, no clock), Timed (beat a 3-minute countdown), Zen (fully relaxed, no timer), and Daily '
  'Puzzle (one seeded grid shared by everyone each day). Every on-screen control — hint, pause, '
  'restart — is itself a hover-dwell button, and a two-hands-raised gesture restarts the level '
  'instantly, so nothing in the game ever needs a click. An SVG overlay animates the traced path with '
  'a glowing stroke; found words lock in a permanent highlight; incorrect traces fade out with no '
  'penalty. Web Audio synthesis handles every sound cue (hover tick, letter select, path connect, word '
  'found, fail fade, victory chord) and progress/best-times/hints-used persist to localStorage.',
  'A gesture-only word search: hover to start, trace with your hand, open palm to confirm the word.',
  'Puzzle',
  (select id from public.categories where slug = 'puzzle' limit 1),
  'single',
  1,
  1,
  'from-violet-950 via-slate-900 to-fuchsia-950',
  '#A78BFA',
  4.7,
  2026,
  8,
  'medium',
  '6-12',
  'published',
  false
)
on conflict (id) do update set
  title             = excluded.title,
  tagline           = excluded.tagline,
  description       = excluded.description,
  short_description = excluded.short_description,
  category          = excluded.category,
  category_id       = excluded.category_id,
  players           = excluded.players,
  min_players       = excluded.min_players,
  max_players       = excluded.max_players,
  cover             = excluded.cover,
  accent            = excluded.accent,
  rating            = excluded.rating,
  release_year      = excluded.release_year,
  duration_minutes  = excluded.duration_minutes,
  difficulty        = excluded.difficulty,
  age_group         = excluded.age_group,
  status            = excluded.status,
  featured          = excluded.featured,
  updated_at        = now();

-- ----------------------------------------------------------------------------
-- Optional: verify the scores wiring after a few plays.
--
--   select s.score, s.achieved_at, u.name
--   from public.scores s
--   join public.users u on u.id = s.user_id
--   where s.game_id = 'word-search-hidden-words'
--   order by s.score desc
--   limit 10;
-- ----------------------------------------------------------------------------
