export const STATES = {
  LOADING: 'LOADING',
  IDLE: 'IDLE',
  DETECTED: 'DETECTED',
  COUNTDOWN: 'COUNTDOWN',
  CHALLENGE: 'CHALLENGE',
  FEEDBACK: 'FEEDBACK',
  GAME_OVER: 'GAME_OVER',
  PAUSED: 'PAUSED',
};

export const DIFFICULTY = {
  EASY: 1,
  MEDIUM: 2,
  HARD: 3,
  EXPERT: 4,
};

// MediaPipe Pose landmark indices
export const LM = {
  NOSE: 0,
  LEFT_EYE_INNER: 1,
  LEFT_EYE: 2,
  LEFT_EYE_OUTER: 3,
  RIGHT_EYE_INNER: 4,
  RIGHT_EYE: 5,
  RIGHT_EYE_OUTER: 6,
  LEFT_EAR: 7,
  RIGHT_EAR: 8,
  LEFT_SHOULDER: 11,
  RIGHT_SHOULDER: 12,
  LEFT_ELBOW: 13,
  RIGHT_ELBOW: 14,
  LEFT_WRIST: 15,
  RIGHT_WRIST: 16,
  LEFT_HIP: 23,
  RIGHT_HIP: 24,
  LEFT_KNEE: 25,
  RIGHT_KNEE: 26,
  LEFT_ANKLE: 27,
  RIGHT_ANKLE: 28,
  LEFT_HEEL: 29,
  RIGHT_HEEL: 30,
  LEFT_FOOT_INDEX: 31,
  RIGHT_FOOT_INDEX: 32,
};

export const GAME_CONFIG = {
  POSES_PER_ROUND: 12,
  POSE_TIME_BY_DIFFICULTY: { 1: 6, 2: 5, 3: 4, 4: 3 },
  ACCURACY_THRESHOLDS: { PERFECT: 88, GOOD: 68, TRYAGAIN: 0 },
  DETECTION_HOLD_MS: 3000,
  HANDS_UP_HOLD_MS: 2000,
  CLAP_MAX_DISTANCE: 0.12,
  FREEZE_THRESHOLD: 0.008,
  FREEZE_HOLD_MS: 3000,
  FEEDBACK_DURATION_MS: 1800,
  COMBO_MULTIPLIERS: [1, 1.25, 1.5, 2, 2.5, 3],
  SPEED_BONUS_MAX: 1.5,
  SCORE_BASE: 100,
  SMOOTHING_ALPHA: 0.35,
};

export const COLORS = {
  PRIMARY: '#00f5ff',
  SECONDARY: '#ff0080',
  ACCENT: '#ffff00',
  SUCCESS: '#00ff88',
  WARNING: '#ff8800',
  ERROR: '#ff2244',
  SKELETON_PLAYER: '#00f5ff',
  SKELETON_TARGET: '#ff0080',
  BG: '#0a0a1a',
};
