/** Six visual environment themes that rotate as the player progresses. */
import type { Environment } from '../../types';
import { ENV_CHANGE_INTERVAL } from '../../constants/gameConfig';

export const ENVIRONMENTS: Environment[] = [
  {
    name:           'Forest',
    emoji:          '🌲',
    skyTop:         '#1a6b3a',
    skyBottom:      '#a8d8a8',
    terrainFill:    '#3a5c2a',
    terrainStroke:  '#2d4a1e',
    terrainSurface: '#4a7c32',
    cloudColor:     '#e8f5e9',
    mountainColor:  '#2d5a27',
    treeColor:      '#2e7d32',
    treeTrunkColor: '#5d4037',
    ambientColor:   '#a5d6a7',
    fogColor:       'rgba(144,202,140,0.15)',
    accentColor:    '#FFE878',
    sunColor:       '#FFF176',
    hasSnow:  false, hasLava: false, hasCactus: false, hasCandy: false,
  },
  {
    name:           'Desert',
    emoji:          '🌵',
    skyTop:         '#FF8C00',
    skyBottom:      '#FFD54F',
    terrainFill:    '#c8a06a',
    terrainStroke:  '#a07040',
    terrainSurface: '#d4a574',
    cloudColor:     '#FFE0B2',
    mountainColor:  '#bf6b28',
    treeColor:      '#4caf50',  // cactus green
    treeTrunkColor: '#2e7d32',
    ambientColor:   '#FFCC80',
    fogColor:       'rgba(255,180,80,0.12)',
    accentColor:    '#FF6B35',
    sunColor:       '#FF8F00',
    hasSnow:  false, hasLava: false, hasCactus: true, hasCandy: false,
  },
  {
    name:           'Snow',
    emoji:          '❄️',
    skyTop:         '#1a237e',
    skyBottom:      '#90CAF9',
    terrainFill:    '#e8eaf6',
    terrainStroke:  '#9fa8da',
    terrainSurface: '#ffffff',
    cloudColor:     '#E3F2FD',
    mountainColor:  '#c5cae9',
    treeColor:      '#37474f',
    treeTrunkColor: '#5d4037',
    ambientColor:   '#B3E5FC',
    fogColor:       'rgba(200,220,255,0.18)',
    accentColor:    '#82B1FF',
    sunColor:       '#FFF9C4',
    hasSnow:  true, hasLava: false, hasCactus: false, hasCandy: false,
  },
  {
    name:           'Volcano',
    emoji:          '🌋',
    skyTop:         '#b71c1c',
    skyBottom:      '#e53935',
    terrainFill:    '#212121',
    terrainStroke:  '#3e2723',
    terrainSurface: '#424242',
    cloudColor:     '#EF9A9A',
    mountainColor:  '#1a1a1a',
    treeColor:      '#4e342e',
    treeTrunkColor: '#3e2723',
    ambientColor:   '#FF5252',
    fogColor:       'rgba(255,80,0,0.18)',
    accentColor:    '#FF6D00',
    sunColor:       '#FF3D00',
    hasSnow:  false, hasLava: true, hasCactus: false, hasCandy: false,
  },
  {
    name:           'Moon',
    emoji:          '🌕',
    skyTop:         '#000000',
    skyBottom:      '#0d1b2a',
    terrainFill:    '#546e7a',
    terrainStroke:  '#37474f',
    terrainSurface: '#78909c',
    cloudColor:     'rgba(255,255,255,0.2)',
    mountainColor:  '#455a64',
    treeColor:      '#37474f',
    treeTrunkColor: '#263238',
    ambientColor:   '#80DEEA',
    fogColor:       'rgba(80,100,130,0.15)',
    accentColor:    '#80DEEA',
    sunColor:       '#FFF9C4',
    hasSnow:  false, hasLava: false, hasCactus: false, hasCandy: false,
  },
  {
    name:           'Candy World',
    emoji:          '🍭',
    skyTop:         '#AD1457',
    skyBottom:      '#F48FB1',
    terrainFill:    '#e91e63',
    terrainStroke:  '#c2185b',
    terrainSurface: '#f06292',
    cloudColor:     '#FCE4EC',
    mountainColor:  '#c2185b',
    treeColor:      '#AB47BC',
    treeTrunkColor: '#7B1FA2',
    ambientColor:   '#F48FB1',
    fogColor:       'rgba(244,143,177,0.15)',
    accentColor:    '#FF80AB',
    sunColor:       '#FF80AB',
    hasSnow:  false, hasLava: false, hasCactus: false, hasCandy: true,
  },
];

export function getEnvironmentForDistance(distance: number): Environment {
  const idx = Math.floor(distance / ENV_CHANGE_INTERVAL) % ENVIRONMENTS.length;
  return ENVIRONMENTS[idx];
}

export function getEnvironmentIndex(distance: number): number {
  return Math.floor(distance / ENV_CHANGE_INTERVAL) % ENVIRONMENTS.length;
}
