// ============================================================
//  FLAGS QUIZ — Country & Continent Data
// ============================================================

export const CONTINENTS = {
  europe:   { label: 'Europe',   emoji: '🇪🇺', color: '#2196f3' },
  asia:     { label: 'Asia',     emoji: '🌏', color: '#ff9800' },
  africa:   { label: 'Africa',   emoji: '🌍', color: '#4caf50' },
  americas: { label: 'Americas', emoji: '🌎', color: '#f44336' },
  oceania:  { label: 'Oceania',  emoji: '🌊', color: '#00bcd4' },
  world:    { label: 'World Mix',emoji: '🌐', color: '#9c27b0' },
};

export const CAMPAIGN_STAGES = [
  { id: 'europe',   label: 'Europe',      emoji: '🇪🇺', required: 8  },
  { id: 'asia',     label: 'Asia',        emoji: '🌏', required: 8  },
  { id: 'africa',   label: 'Africa',      emoji: '🌍', required: 8  },
  { id: 'americas', label: 'Americas',    emoji: '🌎', required: 8  },
  { id: 'world',    label: 'World Final', emoji: '🌐', required: 12 },
];

export const ARCADE_CONTINENTS = [
  { id: 'europe',   label: 'Europe',   emoji: '🇪🇺', color: '#2196f3' },
  { id: 'asia',     label: 'Asia',     emoji: '🌏', color: '#ff9800' },
  { id: 'africa',   label: 'Africa',   emoji: '🌍', color: '#4caf50' },
  { id: 'americas', label: 'Americas', emoji: '🌎', color: '#f44336' },
  { id: 'world',    label: 'Hard Mix', emoji: '🌐', color: '#9c27b0' },
];

export function flagUrl(code) {
  return `https://flagcdn.com/w320/${code}.png`;
}

export const COUNTRIES = [
  // ── Europe ──────────────────────────────────────────────
  { code: 'al', name: 'Albania',               continent: 'europe' },
  { code: 'ad', name: 'Andorra',               continent: 'europe' },
  { code: 'at', name: 'Austria',               continent: 'europe' },
  { code: 'by', name: 'Belarus',               continent: 'europe' },
  { code: 'be', name: 'Belgium',               continent: 'europe' },
  { code: 'ba', name: 'Bosnia and Herzegovina', continent: 'europe' },
  { code: 'bg', name: 'Bulgaria',              continent: 'europe' },
  { code: 'hr', name: 'Croatia',               continent: 'europe' },
  { code: 'cy', name: 'Cyprus',                continent: 'europe' },
  { code: 'cz', name: 'Czech Republic',        continent: 'europe' },
  { code: 'dk', name: 'Denmark',               continent: 'europe' },
  { code: 'ee', name: 'Estonia',               continent: 'europe' },
  { code: 'fi', name: 'Finland',               continent: 'europe' },
  { code: 'fr', name: 'France',                continent: 'europe' },
  { code: 'ge', name: 'Georgia',               continent: 'europe' },
  { code: 'de', name: 'Germany',               continent: 'europe' },
  { code: 'gr', name: 'Greece',                continent: 'europe' },
  { code: 'hu', name: 'Hungary',               continent: 'europe' },
  { code: 'is', name: 'Iceland',               continent: 'europe' },
  { code: 'ie', name: 'Ireland',               continent: 'europe' },
  { code: 'it', name: 'Italy',                 continent: 'europe' },
  { code: 'lv', name: 'Latvia',                continent: 'europe' },
  { code: 'li', name: 'Liechtenstein',         continent: 'europe' },
  { code: 'lt', name: 'Lithuania',             continent: 'europe' },
  { code: 'lu', name: 'Luxembourg',            continent: 'europe' },
  { code: 'mt', name: 'Malta',                 continent: 'europe' },
  { code: 'md', name: 'Moldova',               continent: 'europe' },
  { code: 'mc', name: 'Monaco',                continent: 'europe' },
  { code: 'me', name: 'Montenegro',            continent: 'europe' },
  { code: 'nl', name: 'Netherlands',           continent: 'europe' },
  { code: 'mk', name: 'North Macedonia',       continent: 'europe' },
  { code: 'no', name: 'Norway',                continent: 'europe' },
  { code: 'pl', name: 'Poland',                continent: 'europe' },
  { code: 'pt', name: 'Portugal',              continent: 'europe' },
  { code: 'ro', name: 'Romania',               continent: 'europe' },
  { code: 'ru', name: 'Russia',                continent: 'europe' },
  { code: 'sm', name: 'San Marino',            continent: 'europe' },
  { code: 'rs', name: 'Serbia',                continent: 'europe' },
  { code: 'sk', name: 'Slovakia',              continent: 'europe' },
  { code: 'si', name: 'Slovenia',              continent: 'europe' },
  { code: 'es', name: 'Spain',                 continent: 'europe' },
  { code: 'se', name: 'Sweden',                continent: 'europe' },
  { code: 'ch', name: 'Switzerland',           continent: 'europe' },
  { code: 'ua', name: 'Ukraine',               continent: 'europe' },
  { code: 'gb', name: 'United Kingdom',        continent: 'europe' },

  // ── Asia ────────────────────────────────────────────────
  { code: 'af', name: 'Afghanistan',           continent: 'asia' },
  { code: 'am', name: 'Armenia',               continent: 'asia' },
  { code: 'az', name: 'Azerbaijan',            continent: 'asia' },
  { code: 'bh', name: 'Bahrain',               continent: 'asia' },
  { code: 'bd', name: 'Bangladesh',            continent: 'asia' },
  { code: 'bt', name: 'Bhutan',                continent: 'asia' },
  { code: 'bn', name: 'Brunei',                continent: 'asia' },
  { code: 'kh', name: 'Cambodia',              continent: 'asia' },
  { code: 'cn', name: 'China',                 continent: 'asia' },
  { code: 'in', name: 'India',                 continent: 'asia' },
  { code: 'id', name: 'Indonesia',             continent: 'asia' },
  { code: 'ir', name: 'Iran',                  continent: 'asia' },
  { code: 'iq', name: 'Iraq',                  continent: 'asia' },
  { code: 'il', name: 'Israel',                continent: 'asia' },
  { code: 'jp', name: 'Japan',                 continent: 'asia' },
  { code: 'jo', name: 'Jordan',                continent: 'asia' },
  { code: 'kz', name: 'Kazakhstan',            continent: 'asia' },
  { code: 'kw', name: 'Kuwait',                continent: 'asia' },
  { code: 'kg', name: 'Kyrgyzstan',            continent: 'asia' },
  { code: 'la', name: 'Laos',                  continent: 'asia' },
  { code: 'lb', name: 'Lebanon',               continent: 'asia' },
  { code: 'my', name: 'Malaysia',              continent: 'asia' },
  { code: 'mv', name: 'Maldives',              continent: 'asia' },
  { code: 'mn', name: 'Mongolia',              continent: 'asia' },
  { code: 'mm', name: 'Myanmar',               continent: 'asia' },
  { code: 'np', name: 'Nepal',                 continent: 'asia' },
  { code: 'kp', name: 'North Korea',           continent: 'asia' },
  { code: 'om', name: 'Oman',                  continent: 'asia' },
  { code: 'pk', name: 'Pakistan',              continent: 'asia' },
  { code: 'ph', name: 'Philippines',           continent: 'asia' },
  { code: 'qa', name: 'Qatar',                 continent: 'asia' },
  { code: 'sa', name: 'Saudi Arabia',          continent: 'asia' },
  { code: 'sg', name: 'Singapore',             continent: 'asia' },
  { code: 'kr', name: 'South Korea',           continent: 'asia' },
  { code: 'lk', name: 'Sri Lanka',             continent: 'asia' },
  { code: 'sy', name: 'Syria',                 continent: 'asia' },
  { code: 'tw', name: 'Taiwan',                continent: 'asia' },
  { code: 'tj', name: 'Tajikistan',            continent: 'asia' },
  { code: 'th', name: 'Thailand',              continent: 'asia' },
  { code: 'tl', name: 'Timor-Leste',           continent: 'asia' },
  { code: 'tm', name: 'Turkmenistan',          continent: 'asia' },
  { code: 'ae', name: 'United Arab Emirates',  continent: 'asia' },
  { code: 'uz', name: 'Uzbekistan',            continent: 'asia' },
  { code: 'vn', name: 'Vietnam',               continent: 'asia' },
  { code: 'ye', name: 'Yemen',                 continent: 'asia' },

  // ── Africa ──────────────────────────────────────────────
  { code: 'dz', name: 'Algeria',               continent: 'africa' },
  { code: 'ao', name: 'Angola',                continent: 'africa' },
  { code: 'bj', name: 'Benin',                 continent: 'africa' },
  { code: 'bw', name: 'Botswana',              continent: 'africa' },
  { code: 'bf', name: 'Burkina Faso',          continent: 'africa' },
  { code: 'bi', name: 'Burundi',               continent: 'africa' },
  { code: 'cm', name: 'Cameroon',              continent: 'africa' },
  { code: 'cv', name: 'Cabo Verde',            continent: 'africa' },
  { code: 'cf', name: 'Central African Republic', continent: 'africa' },
  { code: 'td', name: 'Chad',                  continent: 'africa' },
  { code: 'km', name: 'Comoros',               continent: 'africa' },
  { code: 'cd', name: 'DR Congo',              continent: 'africa' },
  { code: 'cg', name: 'Republic of the Congo', continent: 'africa' },
  { code: 'dj', name: 'Djibouti',              continent: 'africa' },
  { code: 'eg', name: 'Egypt',                 continent: 'africa' },
  { code: 'gq', name: 'Equatorial Guinea',     continent: 'africa' },
  { code: 'er', name: 'Eritrea',               continent: 'africa' },
  { code: 'sz', name: 'Eswatini',              continent: 'africa' },
  { code: 'et', name: 'Ethiopia',              continent: 'africa' },
  { code: 'ga', name: 'Gabon',                 continent: 'africa' },
  { code: 'gm', name: 'Gambia',                continent: 'africa' },
  { code: 'gh', name: 'Ghana',                 continent: 'africa' },
  { code: 'gn', name: 'Guinea',                continent: 'africa' },
  { code: 'gw', name: 'Guinea-Bissau',         continent: 'africa' },
  { code: 'ke', name: 'Kenya',                 continent: 'africa' },
  { code: 'ls', name: 'Lesotho',               continent: 'africa' },
  { code: 'lr', name: 'Liberia',               continent: 'africa' },
  { code: 'ly', name: 'Libya',                 continent: 'africa' },
  { code: 'mg', name: 'Madagascar',            continent: 'africa' },
  { code: 'mw', name: 'Malawi',                continent: 'africa' },
  { code: 'ml', name: 'Mali',                  continent: 'africa' },
  { code: 'mr', name: 'Mauritania',            continent: 'africa' },
  { code: 'mu', name: 'Mauritius',             continent: 'africa' },
  { code: 'ma', name: 'Morocco',               continent: 'africa' },
  { code: 'mz', name: 'Mozambique',            continent: 'africa' },
  { code: 'na', name: 'Namibia',               continent: 'africa' },
  { code: 'ne', name: 'Niger',                 continent: 'africa' },
  { code: 'ng', name: 'Nigeria',               continent: 'africa' },
  { code: 'rw', name: 'Rwanda',                continent: 'africa' },
  { code: 'st', name: 'Sao Tome and Principe', continent: 'africa' },
  { code: 'sn', name: 'Senegal',               continent: 'africa' },
  { code: 'sc', name: 'Seychelles',            continent: 'africa' },
  { code: 'sl', name: 'Sierra Leone',          continent: 'africa' },
  { code: 'so', name: 'Somalia',               continent: 'africa' },
  { code: 'za', name: 'South Africa',          continent: 'africa' },
  { code: 'ss', name: 'South Sudan',           continent: 'africa' },
  { code: 'sd', name: 'Sudan',                 continent: 'africa' },
  { code: 'tz', name: 'Tanzania',              continent: 'africa' },
  { code: 'tg', name: 'Togo',                  continent: 'africa' },
  { code: 'tn', name: 'Tunisia',               continent: 'africa' },
  { code: 'ug', name: 'Uganda',                continent: 'africa' },
  { code: 'zm', name: 'Zambia',                continent: 'africa' },
  { code: 'zw', name: 'Zimbabwe',              continent: 'africa' },

  // ── Americas ────────────────────────────────────────────
  { code: 'ag', name: 'Antigua and Barbuda',   continent: 'americas' },
  { code: 'ar', name: 'Argentina',             continent: 'americas' },
  { code: 'bs', name: 'Bahamas',               continent: 'americas' },
  { code: 'bb', name: 'Barbados',              continent: 'americas' },
  { code: 'bz', name: 'Belize',                continent: 'americas' },
  { code: 'bo', name: 'Bolivia',               continent: 'americas' },
  { code: 'br', name: 'Brazil',                continent: 'americas' },
  { code: 'ca', name: 'Canada',                continent: 'americas' },
  { code: 'cl', name: 'Chile',                 continent: 'americas' },
  { code: 'co', name: 'Colombia',              continent: 'americas' },
  { code: 'cr', name: 'Costa Rica',            continent: 'americas' },
  { code: 'cu', name: 'Cuba',                  continent: 'americas' },
  { code: 'dm', name: 'Dominica',              continent: 'americas' },
  { code: 'do', name: 'Dominican Republic',    continent: 'americas' },
  { code: 'ec', name: 'Ecuador',               continent: 'americas' },
  { code: 'sv', name: 'El Salvador',           continent: 'americas' },
  { code: 'gd', name: 'Grenada',               continent: 'americas' },
  { code: 'gt', name: 'Guatemala',             continent: 'americas' },
  { code: 'gy', name: 'Guyana',                continent: 'americas' },
  { code: 'ht', name: 'Haiti',                 continent: 'americas' },
  { code: 'hn', name: 'Honduras',              continent: 'americas' },
  { code: 'jm', name: 'Jamaica',               continent: 'americas' },
  { code: 'mx', name: 'Mexico',                continent: 'americas' },
  { code: 'ni', name: 'Nicaragua',             continent: 'americas' },
  { code: 'pa', name: 'Panama',                continent: 'americas' },
  { code: 'py', name: 'Paraguay',              continent: 'americas' },
  { code: 'pe', name: 'Peru',                  continent: 'americas' },
  { code: 'kn', name: 'Saint Kitts and Nevis', continent: 'americas' },
  { code: 'lc', name: 'Saint Lucia',           continent: 'americas' },
  { code: 'vc', name: 'Saint Vincent',         continent: 'americas' },
  { code: 'sr', name: 'Suriname',              continent: 'americas' },
  { code: 'tt', name: 'Trinidad and Tobago',   continent: 'americas' },
  { code: 'us', name: 'United States',         continent: 'americas' },
  { code: 'uy', name: 'Uruguay',               continent: 'americas' },
  { code: 've', name: 'Venezuela',             continent: 'americas' },

  // ── Oceania (in world pool) ──────────────────────────────
  { code: 'au', name: 'Australia',             continent: 'oceania' },
  { code: 'fj', name: 'Fiji',                  continent: 'oceania' },
  { code: 'fm', name: 'Micronesia',            continent: 'oceania' },
  { code: 'ki', name: 'Kiribati',              continent: 'oceania' },
  { code: 'mh', name: 'Marshall Islands',      continent: 'oceania' },
  { code: 'nr', name: 'Nauru',                 continent: 'oceania' },
  { code: 'nz', name: 'New Zealand',           continent: 'oceania' },
  { code: 'pg', name: 'Papua New Guinea',      continent: 'oceania' },
  { code: 'pw', name: 'Palau',                 continent: 'oceania' },
  { code: 'sb', name: 'Solomon Islands',       continent: 'oceania' },
  { code: 'to', name: 'Tonga',                 continent: 'oceania' },
  { code: 'tv', name: 'Tuvalu',                continent: 'oceania' },
  { code: 'vu', name: 'Vanuatu',               continent: 'oceania' },
  { code: 'ws', name: 'Samoa',                 continent: 'oceania' },
];

export function getCountriesByContinent(continent) {
  if (continent === 'world') return COUNTRIES;
  return COUNTRIES.filter(c => c.continent === continent);
}
